# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8151ae91464f3ca220715a954406286362a055b79e2d8742b7242069641c1aac2756cdc91bd91eab8e1533ebaa47413edeb3a3a4bcb48cc8faa3e89518ccdeec

test:
  secret_key_base: fd340c942be3224dbe3805389488c86deb039f776a4c10324985c10675cf8895d4f4c90b8ed0859452b012a444f70a6373d0abca4658def9af04eccdba675331

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
